name: CI

on: [issues, issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        npm install --user
    - name: run node script
      env:
        GITHUB_LOGIN: wangsq-web
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node index.js
    - name: config git info
      run: |
        git config --global user.email "1475088311@qq.com"
        git config --global user.name "wangsq-web"
    - name: commit change
      run: |
        git checkout master
        git add .
        git commit -m "Update from Github Action"
    - name: push change
      env:
        GITHUB_LOGIN: wangsq-web
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
    - name: done
      run: echo 'done'
